### ISSUE TITLE
Calculation of year stem and branch

### ISSUE THREAD

**Issue by benyaminshoham** [williampan/calendar#1]
Hello my friend :)

Thank you for your calendar, I was looking for such code for a long time.

Mind you that the calculation of the stem and branch for the year are wrong. They are calculated for the gregorian year, and they should be calculated for the sexagenary cycle year.

According to Wikipedia, this code should do it:

`var SexaYear = (y-3)%60;`

**Comment by williampan** [comment]
Hi Benyamin, 

Thanks for looking at this! I'm not sure what you mean -- the call to toLocaleString (line 39), for most browsers, returns a Chinese date with a sexagenary year, not the Gregorian year. Thus, the calculations in lines 50-55 should be correct. Please let me know if this isn't the case. (I know some browsers implement toLocaleString differently -- so this might be a browser-specific issue, which would be hard to fix.)

**Comment by benyaminshoham** [comment]
Ok, I will test with different browsers and let you know.

On a different note: This calendar show stem and branch for each year. Do
you happen to know the logic for calculating the stem and branch for month,
day and hour too? (four pillars / eight characters)

Best,

B


Benyamin Shoham

**Comment by williampan** [comment]
I'm afraid I don't know the logic beyond what I've implemented — sorry!
